# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://PathDB.com
title: PathDB
email: max@pathdb.com
author: Max Sumrall
description: > # "Write an awesome description for your new site here. 
  PathDB, a data store for path shaped data. Use PathDB to super-charge your path-oriented graph queries. Built by a Graph Database expert,
  PathDB is an easy way to store and query your data. Primarliy used adjacent to fully-featured database as a graph-specific index.
   Written by Max Sumrall, at http://www.maxsumrall.com or @MaxSumrall.
copyright: 'Copyright &copy; 2016 Max Sumrall. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/maxsumrall
  - title: github
    url: https://github.com/maxsumrall/pathdb
#  - title: linkedin
#    url:
