package bptree;

import bptree.impl.LeafNode;

import java.util.Iterator;

/**
 *  A cursor generated by the index when performing a search.
 */
public interface Cursor extends Iterator<Long[]> {

    Long[] next();

    boolean hasNext();

    int size();

    LeafNode getCurrentLeaf();
}
